version: '3.8'

services:
  brain:
    image: ghcr.io/neooriginal/omi.me-apps/brain:latest
    container_name: omi-brain
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENAI_API_KEY=${OPENROUTER_API_KEY:-${OPENAI_API_KEY}}
      - SESSION_SECRET=${SESSION_SECRET}
      - FRONTEND_URL_BRAIN=${FRONTEND_URL_BRAIN:-http://localhost:3000}
    restart: unless-stopped
    networks:
      - omi-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  friend:
    image: ghcr.io/neooriginal/omi.me-apps/friend:latest
    container_name: omi-friend
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENAI_API_KEY=${OPENROUTER_API_KEY:-${OPENAI_API_KEY}}
    restart: unless-stopped
    networks:
      - omi-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  jarvis:
    image: ghcr.io/neooriginal/omi.me-apps/jarvis:latest
    container_name: omi-jarvis
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    restart: unless-stopped
    networks:
      - omi-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  omi-network:
    driver: bridge

volumes:
  brain_data:
  friend_data:
  jarvis_data: 