name: omi-apps
region: nyc
services:
- build_command: cd Brain && npm install
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: eulicesl/OMI.me-Apps
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xxs
  name: brain
  run_command: cd Brain && npm start
  source_dir: /
  envs:
  - key: NODE_ENV
    scope: RUN_TIME
    value: production
  - key: PORT
    scope: RUN_TIME
    value: "3000"
  - key: SUPABASE_URL
    scope: RUN_TIME
    type: SECRET
    value: YOUR_SUPABASE_URL
  - key: SUPABASE_ANON_KEY
    scope: RUN_TIME
    type: SECRET
    value: YOUR_SUPABASE_ANON_KEY
  - key: OPENROUTER_API_KEY
    scope: RUN_TIME
    type: SECRET
    value: YOUR_OPENROUTER_API_KEY
  - key: SESSION_SECRET
    scope: RUN_TIME
    type: SECRET
    value: YOUR_SESSION_SECRET

- build_command: cd Friend && npm install
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: eulicesl/OMI.me-Apps
  http_port: 5000
  instance_count: 1
  instance_size_slug: basic-xxs
  name: friend
  run_command: cd Friend && npm start
  source_dir: /
  envs:
  - key: NODE_ENV
    scope: RUN_TIME
    value: production
  - key: PORT
    scope: RUN_TIME
    value: "5000"
  - key: SUPABASE_URL
    scope: RUN_TIME
    type: SECRET
    value: YOUR_SUPABASE_URL
  - key: SUPABASE_ANON_KEY
    scope: RUN_TIME
    type: SECRET
    value: YOUR_SUPABASE_ANON_KEY
  - key: OPENROUTER_API_KEY
    scope: RUN_TIME
    type: SECRET
    value: YOUR_OPENROUTER_API_KEY

- build_command: cd Jarvis && npm install
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: eulicesl/OMI.me-Apps
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xxs
  name: jarvis
  run_command: cd Jarvis && npm start
  source_dir: /
  envs:
  - key: NODE_ENV
    scope: RUN_TIME
    value: production
  - key: PORT
    scope: RUN_TIME
    value: "8000"
  - key: SUPABASE_URL
    scope: RUN_TIME
    type: SECRET
    value: YOUR_SUPABASE_URL
  - key: SUPABASE_ANON_KEY
    scope: RUN_TIME
    type: SECRET
    value: YOUR_SUPABASE_ANON_KEY